# =================================================
# Monitors
# =================================================

# HKC top
monitor = DP-4, 1920x1080@144.04, 320x0, 1

# ASUS main
monitor = DP-5, 2560x1440@144.01, 0x1080, 1

# RTK bottom - flipped 180 degrees
monitor = HDMI-A-2, 1366x768@59.72, 597x2520, 1, transform, 2


# =================================================
# Workspace groups
# =================================================

# MAIN ASUS
workspace = 1, monitor:DP-5, default:true
workspace = 2, monitor:DP-5
workspace = 3, monitor:DP-5
workspace = 4, monitor:DP-5
workspace = 5, monitor:DP-5
workspace = 6, monitor:DP-5
workspace = 7, monitor:DP-5
workspace = 8, monitor:DP-5
workspace = 9, monitor:DP-5

# TOP HKC
workspace = 11, monitor:DP-4, default:true
workspace = 12, monitor:DP-4
workspace = 13, monitor:DP-4
workspace = 14, monitor:DP-4
workspace = 15, monitor:DP-4
workspace = 16, monitor:DP-4
workspace = 17, monitor:DP-4
workspace = 18, monitor:DP-4
workspace = 19, monitor:DP-4

# BOTTOM RTK
workspace = 21, monitor:HDMI-A-2, default:true
workspace = 22, monitor:HDMI-A-2
workspace = 23, monitor:HDMI-A-2
workspace = 24, monitor:HDMI-A-2
workspace = 25, monitor:HDMI-A-2
workspace = 26, monitor:HDMI-A-2
workspace = 27, monitor:HDMI-A-2
workspace = 28, monitor:HDMI-A-2
workspace = 29, monitor:HDMI-A-2
